# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 20:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20161014_1526'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-creation_time',)},
        ),
    ]
